package org.projectshop.pojo;

import org.projectshop.pojo.BasePojo;

public class Movice extends BasePojo {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movice.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movice.enname
     *
     * @mbggenerated
     */
    private String enname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movice.point
     *
     * @mbggenerated
     */
    private Double point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movice.picurl
     *
     * @mbggenerated
     */
    private String picurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movice.make_state
     *
     * @mbggenerated
     */
    private String makeState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movice.language
     *
     * @mbggenerated
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movice.release_date
     *
     * @mbggenerated
     */
    private String releaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movice.filmlen
     *
     * @mbggenerated
     */
    private String filmlen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movice.other_name
     *
     * @mbggenerated
     */
    private String otherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movice.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movice.url
     *
     * @mbggenerated
     */
    private String url;

    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movice.name
     *
     * @param name the value for movice.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movice.enname
     *
     * @return the value of movice.enname
     *
     * @mbggenerated
     */
    public String getEnname() {
        return enname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movice.enname
     *
     * @param enname the value for movice.enname
     *
     * @mbggenerated
     */
    public void setEnname(String enname) {
        this.enname = enname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movice.point
     *
     * @return the value of movice.point
     *
     * @mbggenerated
     */
    public Double getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movice.point
     *
     * @param point the value for movice.point
     *
     * @mbggenerated
     */
    public void setPoint(Double point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movice.picurl
     *
     * @return the value of movice.picurl
     *
     * @mbggenerated
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movice.picurl
     *
     * @param picurl the value for movice.picurl
     *
     * @mbggenerated
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movice.make_state
     *
     * @return the value of movice.make_state
     *
     * @mbggenerated
     */
    public String getMakeState() {
        return makeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movice.make_state
     *
     * @param makeState the value for movice.make_state
     *
     * @mbggenerated
     */
    public void setMakeState(String makeState) {
        this.makeState = makeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movice.language
     *
     * @return the value of movice.language
     *
     * @mbggenerated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movice.language
     *
     * @param language the value for movice.language
     *
     * @mbggenerated
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movice.release_date
     *
     * @return the value of movice.release_date
     *
     * @mbggenerated
     */
    public String getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movice.release_date
     *
     * @param releaseDate the value for movice.release_date
     *
     * @mbggenerated
     */
    public void setReleaseDate(String releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movice.filmlen
     *
     * @return the value of movice.filmlen
     *
     * @mbggenerated
     */
    public String getFilmlen() {
        return filmlen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movice.filmlen
     *
     * @param filmlen the value for movice.filmlen
     *
     * @mbggenerated
     */
    public void setFilmlen(String filmlen) {
        this.filmlen = filmlen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movice.other_name
     *
     * @return the value of movice.other_name
     *
     * @mbggenerated
     */
    public String getOtherName() {
        return otherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movice.other_name
     *
     * @param otherName the value for movice.other_name
     *
     * @mbggenerated
     */
    public void setOtherName(String otherName) {
        this.otherName = otherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movice.detail
     *
     * @return the value of movice.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movice.detail
     *
     * @param detail the value for movice.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movice.url
     *
     * @return the value of movice.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movice.url
     *
     * @param url the value for movice.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }


}